# Generated by Django 4.0.2 on 2022-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.Skill'),
        ),
    ]
